'use client'

import {
  Profile,
  Sport,
  AthleteSport,
  Match,
  Message,
  PerformanceRecord,
  Achievement,
} from "@/types/database"

export const INITIAL_SPORTS: Sport[] = [
  { id: "cricket", name: "Cricket", icon: "Bat", category: "Team" },
  { id: "football", name: "Football", icon: "Trophy", category: "Team" },
  { id: "badminton", name: "Badminton", icon: "Activity", category: "Racquet" },
  { id: "running", name: "Running", icon: "Zap", category: "Athletics" },
  { id: "swimming", name: "Swimming", icon: "Waves", category: "Water" },
  { id: "tennis", name: "Tennis", icon: "Target", category: "Racquet" },
  { id: "basketball", name: "Basketball", icon: "Circle", category: "Team" },
  { id: "chess", name: "Chess", icon: "Crown", category: "Strategy" },
]

export const CURRENT_USER: Profile = {
  id: "usr_varun_01",
  username: "varungangam",
  full_name: "Varun Gangam",
  avatar_url: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
  bio: "All-rounder in Cricket & Box-to-Box Midfielder in Football. Love weekend competitive matches and tracking fitness.",
  city: "Bangalore (Indiranagar)",
  latitude: 12.9716,
  longitude: 77.5946,
  verification_status: "verified",
  role: "athlete",
  rating: 4.9,
  matches_played: 34,
  win_rate: 76,
  created_at: "2025-01-15T10:00:00Z",
}

export const CURRENT_USER_SPORTS: AthleteSport[] = [
  {
    id: "as_01",
    profile_id: "usr_varun_01",
    sport_id: "cricket",
    sport_name: "Cricket",
    sport_icon: "Bat",
    skill_level: "Advanced",
    experience_years: 6,
    sport_data: {
      role: "All-Rounder",
      battingStyle: "Right-Hand Bat",
      bowlingStyle: "Right-Arm Medium Fast",
      battingAverage: 38.4,
      strikeRate: 142.5,
      wicketsTaken: 47,
      bestBowling: "4/18",
      jerseyNumber: 18,
    },
  },
  {
    id: "as_02",
    profile_id: "usr_varun_01",
    sport_id: "football",
    sport_name: "Football",
    sport_icon: "Trophy",
    skill_level: "Intermediate",
    experience_years: 4,
    sport_data: {
      position: "Center Midfielder (CM)",
      preferredFoot: "Right",
      goalsScored: 19,
      assists: 28,
      matchesPlayed: 42,
    },
  },
  {
    id: "as_03",
    profile_id: "usr_varun_01",
    sport_id: "badminton",
    sport_name: "Badminton",
    sport_icon: "Activity",
    skill_level: "Advanced",
    experience_years: 5,
    sport_data: {
      formatPreference: "Doubles & Singles",
      racketType: "Yonex Astrox 88D Pro",
      smashSpeedKmph: 245,
      localRanking: "#12 Indiranagar Club",
    },
  },
  {
    id: "as_04",
    profile_id: "usr_varun_01",
    sport_id: "running",
    sport_name: "Running",
    sport_icon: "Zap",
    skill_level: "Intermediate",
    experience_years: 3,
    sport_data: {
      personalBest5k: "21:40 min",
      personalBest10k: "46:15 min",
      weeklyDistanceKm: 28,
    },
  },
]

export const SEED_ATHLETES: Array<{ profile: Profile; athleteSports: AthleteSport[] }> = [
  {
    profile: {
      id: "usr_rahul_02",
      username: "rahulsharma",
      full_name: "Rahul Sharma",
      avatar_url: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
      bio: "Top-order batsman & wicketkeeper. Looking for competitive weekend games in Koramangala/Indiranagar.",
      city: "Bangalore (Koramangala)",
      latitude: 12.9352,
      longitude: 77.6245,
      verification_status: "verified",
      role: "athlete",
      rating: 4.8,
      matches_played: 52,
      win_rate: 81,
      created_at: "2025-02-10T12:00:00Z",
    },
    athleteSports: [
      {
        id: "as_rahul_01",
        profile_id: "usr_rahul_02",
        sport_id: "cricket",
        sport_name: "Cricket",
        sport_icon: "Bat",
        skill_level: "Advanced",
        experience_years: 8,
        sport_data: {
          role: "Wicketkeeper Batsman",
          battingStyle: "Right-Hand Bat",
          battingAverage: 45.2,
          strikeRate: 154.0,
        },
      },
    ],
  },
  {
    profile: {
      id: "usr_arjun_03",
      username: "arjunkumar",
      full_name: "Arjun Kumar",
      avatar_url: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
      bio: "Pace bowler and passionate cricketer. Always ready for evening net sessions and weekend turf matches.",
      city: "Bangalore (Domlur)",
      latitude: 12.9609,
      longitude: 77.6387,
      verification_status: "verified",
      role: "athlete",
      rating: 4.5,
      matches_played: 29,
      win_rate: 68,
      created_at: "2025-03-01T09:00:00Z",
    },
    athleteSports: [
      {
        id: "as_arjun_01",
        profile_id: "usr_arjun_03",
        sport_id: "cricket",
        sport_name: "Cricket",
        sport_icon: "Bat",
        skill_level: "Intermediate",
        experience_years: 4,
        sport_data: {
          role: "Fast Bowler",
          bowlingStyle: "Right-Arm Fast (125 km/h)",
          wicketsTaken: 38,
        },
      },
    ],
  },
  {
    profile: {
      id: "usr_priya_04",
      username: "priyapatel",
      full_name: "Priya Patel",
      avatar_url: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
      bio: "State-level badminton player & coach. Looking for advanced sparring partners and coaching enthusiasts.",
      city: "Bangalore (HSR Layout)",
      latitude: 12.9121,
      longitude: 77.6446,
      verification_status: "verified",
      role: "coach",
      rating: 4.95,
      matches_played: 88,
      win_rate: 89,
      created_at: "2024-11-20T14:00:00Z",
    },
    athleteSports: [
      {
        id: "as_priya_01",
        profile_id: "usr_priya_04",
        sport_id: "badminton",
        sport_name: "Badminton",
        sport_icon: "Activity",
        skill_level: "Professional",
        experience_years: 10,
        sport_data: {
          formatPreference: "Singles & Mixed Doubles",
          smashSpeedKmph: 290,
          ranking: "State Top 10",
        },
      },
    ],
  },
  {
    profile: {
      id: "usr_rohit_05",
      username: "rohitv",
      full_name: "Rohit Varma",
      avatar_url: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80",
      bio: "Striker / Winger in 7-a-side and 11-a-side leagues. High work rate and team player.",
      city: "Bangalore (Indiranagar)",
      latitude: 12.9784,
      longitude: 77.6408,
      verification_status: "verified",
      role: "athlete",
      rating: 4.7,
      matches_played: 45,
      win_rate: 74,
      created_at: "2025-01-28T16:00:00Z",
    },
    athleteSports: [
      {
        id: "as_rohit_01",
        profile_id: "usr_rohit_05",
        sport_id: "football",
        sport_name: "Football",
        sport_icon: "Trophy",
        skill_level: "Advanced",
        experience_years: 7,
        sport_data: {
          position: "Striker (ST)",
          preferredFoot: "Both",
          goalsScored: 44,
          topSpeedKmph: 31.2,
        },
      },
    ],
  },
  {
    profile: {
      id: "usr_ananya_06",
      username: "ananyarun",
      full_name: "Ananya Roy",
      avatar_url: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80",
      bio: "Marathon runner & pacer. Building weekend 10k running clusters in Cubbon Park & Ulsoor.",
      city: "Bangalore (Ulsoor)",
      latitude: 12.9815,
      longitude: 77.6201,
      verification_status: "verified",
      role: "athlete",
      rating: 4.9,
      matches_played: 61,
      win_rate: 92,
      created_at: "2024-12-15T08:00:00Z",
    },
    athleteSports: [
      {
        id: "as_ananya_01",
        profile_id: "usr_ananya_06",
        sport_id: "running",
        sport_name: "Running",
        sport_icon: "Zap",
        skill_level: "Advanced",
        experience_years: 5,
        sport_data: {
          marathonPB: "3h 24m",
          pace10k: "4:15 min/km",
          shoes: "Nike Vaporfly 3",
        },
      },
    ],
  },
]

export const INITIAL_MATCHES: Match[] = [
  {
    id: "match_01",
    creator_id: "usr_rahul_02",
    creator_name: "Rahul Sharma",
    creator_avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    sport_id: "cricket",
    sport_name: "Cricket",
    sport_icon: "Bat",
    title: "Weekend T20 Friendly Match (Turf Underlights)",
    description: "Looking for 4 more players for 11-a-side leather ball game. Turf reserved, white kit preferred.",
    location: "Decathlon Play Arena, Sarjapur Road",
    city: "Bangalore",
    latitude: 12.9081,
    longitude: 77.6833,
    skill_level: "Intermediate",
    start_time: "Saturday, 6:30 PM",
    max_players: 22,
    current_players: 18,
    status: "open",
    participants: [
      {
        match_id: "match_01",
        profile_id: "usr_rahul_02",
        profile_name: "Rahul Sharma",
        profile_avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
        skill_level: "Advanced",
        status: "confirmed",
        joined_at: "2025-08-20T10:00:00Z",
      },
      {
        match_id: "match_01",
        profile_id: "usr_varun_01",
        profile_name: "Varun Gangam",
        profile_avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
        skill_level: "Advanced",
        status: "confirmed",
        joined_at: "2025-08-21T11:00:00Z",
      },
    ],
  },
  {
    id: "match_02",
    creator_id: "usr_rohit_05",
    creator_name: "Rohit Varma",
    creator_avatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80",
    sport_id: "football",
    sport_name: "Football",
    sport_icon: "Trophy",
    title: "5v5 Fast-Paced Turf Football League Match",
    description: "Fast rotation 5-a-side match. High stamina required. Bibs and match ball provided.",
    location: "Kicks on Grass, Bellandur",
    city: "Bangalore",
    latitude: 12.926,
    longitude: 77.6762,
    skill_level: "Advanced",
    start_time: "Sunday, 7:00 AM",
    max_players: 10,
    current_players: 8,
    status: "open",
    participants: [
      {
        match_id: "match_02",
        profile_id: "usr_rohit_05",
        profile_name: "Rohit Varma",
        profile_avatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80",
        skill_level: "Advanced",
        status: "confirmed",
        joined_at: "2025-08-20T12:00:00Z",
      },
    ],
  },
  {
    id: "match_03",
    creator_id: "usr_priya_04",
    creator_name: "Priya Patel",
    creator_avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
    sport_id: "badminton",
    sport_name: "Badminton",
    sport_icon: "Activity",
    title: "Competitive Doubles Sparring Session",
    description: "Looking for 2 intermediate/advanced players to complete 2 sets of intensive doubles sparring.",
    location: "Smash & Strike Badminton Arena, Indiranagar",
    city: "Bangalore",
    latitude: 12.9719,
    longitude: 77.6412,
    skill_level: "Advanced",
    start_time: "Tonight, 8:00 PM",
    max_players: 4,
    current_players: 3,
    status: "open",
    participants: [
      {
        match_id: "match_03",
        profile_id: "usr_priya_04",
        profile_name: "Priya Patel",
        profile_avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
        skill_level: "Professional",
        status: "confirmed",
        joined_at: "2025-08-22T08:00:00Z",
      },
      {
        match_id: "match_03",
        profile_id: "usr_varun_01",
        profile_name: "Varun Gangam",
        profile_avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
        skill_level: "Advanced",
        status: "confirmed",
        joined_at: "2025-08-22T09:30:00Z",
      },
    ],
  },
  {
    id: "match_04",
    creator_id: "usr_ananya_06",
    creator_name: "Ananya Roy",
    creator_avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80",
    sport_id: "running",
    sport_name: "Running",
    sport_icon: "Zap",
    title: "Cubbon Park 10K Sunrise Endurance Run",
    description: "Group pace 5:00 min/km. Hydration stops planned. Beginners to half-marathoners welcome.",
    location: "Cubbon Park Central Gate, MG Road",
    city: "Bangalore",
    latitude: 12.9763,
    longitude: 77.5929,
    skill_level: "Intermediate",
    start_time: "Sunday, 5:45 AM",
    max_players: 30,
    current_players: 24,
    status: "open",
    participants: [],
  },
]

export const INITIAL_MESSAGES: Message[] = [
  {
    id: "msg_01",
    conversation_id: "conv_cricket_01",
    sender_id: "usr_rahul_02",
    sender_name: "Rahul Sharma",
    sender_avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    message: "Hey team! Turf is booked at Sarjapur Play Arena. Please reach 15 mins before 6:30 PM for warmup.",
    created_at: "Today, 4:15 PM",
    is_match_channel: true,
  },
  {
    id: "msg_02",
    conversation_id: "conv_cricket_01",
    sender_id: "usr_varun_01",
    sender_name: "Varun Gangam",
    sender_avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    message: "Sounds great Rahul! I'll bring the extra match leather balls and kit bag.",
    created_at: "Today, 4:20 PM",
    is_match_channel: true,
  },
  {
    id: "msg_03",
    conversation_id: "conv_cricket_01",
    sender_id: "usr_arjun_03",
    sender_name: "Arjun Kumar",
    sender_avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    message: "Awesome. I'm opening the bowling spell in the second innings!",
    created_at: "Today, 4:32 PM",
    is_match_channel: true,
  },
  {
    id: "msg_04",
    conversation_id: "conv_priya_direct",
    sender_id: "usr_priya_04",
    sender_name: "Priya Patel",
    sender_avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
    message: "Hey Varun, are you ready for the 8 PM badminton doubles match tonight at Indiranagar?",
    created_at: "Today, 3:00 PM",
    is_match_channel: false,
  },
]

export const USER_PERFORMANCE: PerformanceRecord[] = [
  {
    id: "perf_01",
    profile_id: "usr_varun_01",
    sport_id: "cricket",
    sport_name: "Cricket",
    metric: "Batting Average",
    value: "38.4",
    unit: "runs/dismissal",
    recorded_at: "Aug 2025",
  },
  {
    id: "perf_02",
    profile_id: "usr_varun_01",
    sport_id: "cricket",
    sport_name: "Cricket",
    metric: "Strike Rate",
    value: "142.5",
    unit: "SR",
    recorded_at: "Aug 2025",
  },
  {
    id: "perf_03",
    profile_id: "usr_varun_01",
    sport_id: "football",
    sport_name: "Football",
    metric: "Pass Accuracy",
    value: "84.2",
    unit: "%",
    recorded_at: "Aug 2025",
  },
  {
    id: "perf_04",
    profile_id: "usr_varun_01",
    sport_id: "running",
    sport_name: "Running",
    metric: "5K Personal Best",
    value: "21:40",
    unit: "min",
    recorded_at: "Jul 2025",
  },
]

export const USER_ACHIEVEMENTS: Achievement[] = [
  {
    id: "ach_01",
    profile_id: "usr_varun_01",
    sport_id: "cricket",
    title: "Man of the Match",
    description: "Scored 58*(28) and took 2 wickets in Bangalore Corporate Cup 2025",
    date: "July 2025",
    badge_icon: "Award",
  },
  {
    id: "ach_02",
    profile_id: "usr_varun_01",
    sport_id: "badminton",
    title: "Tournament Finalist",
    description: "Runner-up in Indiranagar Open Doubles Championship",
    date: "June 2025",
    badge_icon: "Trophy",
  },
  {
    id: "ach_03",
    profile_id: "usr_varun_01",
    sport_id: "running",
    title: "10K Club Finisher",
    description: "Completed Bengaluru 10K Run under 48 minutes",
    date: "May 2025",
    badge_icon: "Medal",
  },
]
